[editor]
line-number = "relative"
bufferline = "always"
auto-completion = true
auto-format = true

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
skip-levels = 2

[editor.soft-wrap]
enable = true

[keys.normal.space]
t = ":sh zellij action new-pane --direction down --close-on-exit -- yazi"
