[editor]
line-number = "relative"
bufferline = "always"
auto-completion = true
auto-format = true

# Anything after --command will be interpreted as a command, so place it at the end
shell = ["nu", "--stdin", "--commands"]

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
skip-levels = 2

[editor.soft-wrap]
enable = true

[keys.normal]
"'" = ":buffer-close"  # Close buffer with single quote
L = ":buffer-next"
H = ":buffer-previous"

[keys.normal.z]
j = "half_page_down" # Not using scroll down(just one line)
k = "half_page_up"   # Not using scroll up(just one line)

[keys.normal.g]
d = ["goto_definition", "align_view_top"]
