[editor]
line-number = "relative"
bufferline = "always"
auto-completion = true
auto-format = true
end-of-line-diagnostics = "hint"
# https://github.com/helix-editor/helix/pull/12213
continue-comments = false

# Anything after --command will be interpreted as a command, so place it at the end
shell = ["nu", "--stdin", "--commands"]

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
skip-levels = 2

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning" # hint | info | warning | error
# other-lines = "hint"

[editor.whitespace.render]
tab = "all"

[keys.normal]
"'" = ":buffer-close"  # Close buffer with single quote
L = ":buffer-next"
H = ":buffer-previous"

[keys.normal.z]
j = "half_page_down" # Not using scroll down(just one line)
k = "half_page_up"   # Not using scroll up(just one line)

[keys.normal.g]
d = ["goto_definition", "align_view_top"]

# window mode
# window modeへの遷移で、space + w, <Ctrl-w>の2パターンあるので両対応する
[keys.normal."space".w]
p = "rotate_view_reverse"

[keys.normal."C-w"]
p = "rotate_view_reverse"
