[env]
HOST = { script = ["hostname"] }

[tasks.apply]
linux_alias = "nixos:apply"
mac_alias = "darwin:apply"

[tasks."xps15:apply"]
description = "Run nixos-rebuild switch"
extend = "nixos:apply"
env = { HOST = "xps15" }

[tasks."nixos:apply"]
script = '''
sudo nixos-rebuild switch --flake ".#${HOST}" --show-trace
'''

[tasks."prox86:apply"]
extend = "darwin:apply"
env = { HOST = "prox86" }

[tasks."fraim:apply"]
extend = "darwin:apply"
env = { HOST = "fraim" }

[tasks."darwin:apply"]
script = '''
nix build .#darwinConfigurations.${HOST}.system --extra-experimental-features 'nix-command flakes' --debug
sudo ./result/sw/bin/darwin-rebuild switch --flake ".#${HOST}"
'''

[tasks.format]
description = "Run formatter"
command = "nix"
args = ["fmt"]

# Should we use nix flake update ?
[tasks.update]
command = "nix"
args = ["flake", "lock", "--update-input", "nixpkgs"]

[tasks.check]
command = "nix"
args = ["flake", "check"]

[tasks.gc]
script = '''
sudo nix profile wipe-history --extra-experimental-features 'nix-command flakes' --profile /nix/var/nix/profiles/system --older-than 7d

sudo nix store gc --debug --extra-experimental-features 'nix-command flakes'
'''

[tasks.clean]
clear = true
script = '''
rm -rf result
'''
