[tasks."xps15:apply"]
description = "Run nixos-rebuild switch"
script = '''
sudo nixos-rebuild switch --flake '.#xps15'
'''

[tasks."darwin:install"]
script = '''
nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer  
./result/bin/darwin-installer
'''

[tasks."prox86:apply"]
script = '''
nix build .#darwinConfigurations.prox86.system --extra-experimental-features 'nix-command flakes'
sudo ./result/sw/bin/darwin-rebuild switch --flake '.#prox86'
'''

[tasks.format]
description = "Run formatter"
command = "nix"
args = ["fmt"]

[tasks.update]
script = '''
nix flake update
'''

[tasks.clean]
script = '''
rm -rf result
'''
