[tasks.deploy]
description = "Deploy to all nodes"
script = '''
deploy --skip-checks --interactive --debug-logs . -- --print-build-logs
'''

[tasks.fmt]
description = "Run nix formatter"
script = '''
nu -c "fd --extension nix . | lines | each { nixfmt $in }"
'''

[tasks.ssh]
description = "SSH to raspi hosts"
script = '''
zellij action new-tab --layout ./etc/rpi.layout.kdl
'''
