[[language]]
name = "yaml"
# does not use ansible-language-server
language-servers = ["yaml-language-server"]
auto-format = false

[language-server.yaml-language-server.config.yaml]
format = { enable = false }
