{ ... }:
{
  imports = [
    ./cloud
    ./container.nix
    ./db.nix
    ./dev.nix
    ./disk.nix
    ./dprint
    ./frontend.nix
    ./fun.nix
    ./git.nix
    ./github.nix
    ./gpg.nix
    ./graphql.nix
    ./hardware.nix
    ./json.nix
    ./kubernetes.nix
    ./languages
    ./mail.nix
    ./man.nix
    ./markdown.nix
    ./monitor.nix
    ./network.nix
    ./observability.nix
    ./provisioning.nix
    ./search.nix
    ./security.nix
    ./toml.nix
    ./typesetting.nix
    ./typo.nix
    ./viewer.nix
    ./viz.nix
    ./wasm.nix
    ./yaml
  ];
}
